language: node_js
node_js:
  - "6"
env:
  - KUNTA_API_BROWSER=phantomjs
before_install: 
 - npm install -g grunt
 - gem install sass
matrix:
  fast_finish: true
env:
  matrix:
    - BROWSER="chrome" VERSION="latest" PLATFORM="linux"
    - BROWSER="chrome" VERSION="latest-1" PLATFORM="linux"
    - BROWSER="firefox" VERSION="latest" PLATFORM="Windows 10"
    - BROWSER="internet explorer" VERSION="latest" PLATFORM="Windows 10"
    - BROWSER="microsoftedge" VERSION="latest" PLATFORM="Windows 10"
    - BROWSER="firefox" VERSION="latest" PLATFORM="Windows 8"
    - BROWSER="internet explorer" VERSION="latest" PLATFORM="Windows 8"
    - BROWSER="safari" VERSION="latest" PLATFORM="macOS 10.12"
    - BROWSER="safari" VERSION="latest" PLATFORM="OS X 10.11"
    - BROWSER="safari" VERSION="latest" PLATFORM="OS X 10.10"
addons:
  sauce_connect:
    username: "vKoivukangas"
    vm-version: dev-varnish
script: 
 - grunt
 - npm run test-coverage