language: node_js
node_js:
  - "6"
  - "7"
env:
  - KUNTA_API_BROWSER=phantomjs
before_install: 
 - npm install -g grunt
 - gem install sass
matrix:
  fast_finish: true
env:
  matrix:
    - SAUCELABS_BROWSER='chrome' SAUCELABS_VERSION='54' SAUCELABS_PLATFORM='Windows 10'
    - SAUCELABS_BROWSER='chrome' SAUCELABS_VERSION='53' SAUCELABS_PLATFORM='Windows 10'
    - SAUCELABS_BROWSER='chrome' SAUCELABS_VERSION='52' SAUCELABS_PLATFORM='Windows 10'
    - SAUCELABS_BROWSER='chrome' SAUCELABS_VERSION='54' SAUCELABS_PLATFORM='Windows 8'
    - SAUCELABS_BROWSER='chrome' SAUCELABS_VERSION='53' SAUCELABS_PLATFORM='Windows 8'
    - SAUCELABS_BROWSER='chrome' SAUCELABS_VERSION='52' SAUCELABS_PLATFORM='Windows 8'
script: 
 - grunt
 - npm run test
 - npm run test-browser