language: node_js
node_js:
  - "6"
  - "7"
env:
  - KUNTA_API_BROWSER=phantomjs
before_install: 
 - npm install -g grunt
 - gem install sass
matrix:
  fast_finish: true
env:
  matrix:
    - BROWSER="chrome" VERSION="54" PLATFORM="Windows 10"
    - BROWSER="chrome" VERSION="54" PLATFORM="Windows 8"
script: 
 - grunt
 - npm run test